DSMYSQL-1561 API Docs update for HA upgrade functionality + DSMYSQL-1559 API Docs update for option to always do full backup for scheduled backup
rackerlabs/docs-cloud-databases pull request #108
Opened 2020-11-06 17:48 UTC by ayersek64

2020-11-06 17:54 UTC, rackernexus commented
Build 83 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c1efe9d35/docs/cloud-databases/v1/). valid for 14 days

2020-11-06 18:08 UTC, catlook requested changes
minor tweaks

2020-11-06 18:08 UTC, catlook commented on api-docs/api-reference/methods/put-update-schedule-for-backups-by-schedule-id-version-accountid-schedules-scheduleid.rst
> +made. When ``day_of_week`` is 0-6, after that day, the schedule will automatically
made. When ``day_of_week`` is 0-6, after that day, the schedule automatically

2020-11-06 18:08 UTC, catlook commented on api-docs/api-reference/methods/put-update-schedule-for-backups-by-schedule-id-version-accountid-schedules-scheduleid.rst
> +run daily incremental backups until the next full backup.
runs daily incremental backups until the next full backup.

2020-11-06 18:08 UTC, catlook commented on api-docs/api-reference/methods/post-create-scheduled-backup-version-accountid-schedules.rst
> +made. When ``day_of_week`` is 0-6, after that day, the schedule will automatically
made. When ``day_of_week`` is 0-6, after that day, the schedule automatically

2020-11-06 18:08 UTC, catlook commented on api-docs/api-reference/methods/post-create-scheduled-backup-version-accountid-schedules.rst
> +run daily incremental backups until the next full backup.
runs daily incremental backups until the next full backup.

2020-11-09 14:21 UTC, catlook commented
@ayersek64 We wrapping this one up today?

2020-11-09 15:11 UTC, ayersek64 commented
Absolutely! <grin>
Just submitted updates for your comments.

2020-11-09 15:17 UTC, catlook approved these changes
👍

2020-11-09 15:18 UTC, rackernexus commented
Build 84 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-21dbb07ef/docs/cloud-databases/v1/). valid for 14 days

2020-11-09 15:19 UTC, merged